/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package InterfaceJava;

import delegaciaprojetoa3.Endereco;
import java.sql.SQLException;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import persistencia.EnderecoDAO;

/**
 *
 * @author yango
 */
public final class CadastroEndereco extends javax.swing.JFrame {

    DefaultTableModel tmContato = new DefaultTableModel(null,new String[]{"Rua","Numero"});
    List<Endereco> Enderecos;
    ListSelectionModel lsmContato;
    /**
     * Creates new form CadastroEndereco
     */
    public CadastroEndereco() {
        initComponents();
        listarEnderecos();
        desabilitaDados();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jBPesquisar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jTRua = new javax.swing.JTextField();
        jLEndereco = new javax.swing.JLabel();
        jTNumero = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTTabela = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jBNovo = new javax.swing.JButton();
        jBAlterarRua = new javax.swing.JButton();
        jBAlteraNum = new javax.swing.JButton();
        jBGravar = new javax.swing.JButton();
        jBExcluir = new javax.swing.JButton();
        jTPesquisa = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBPesquisar.setText("Pesquisar");
        jBPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBPesquisarActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Dados do Endereço"));

        jLabel6.setText("Rua");

        jTRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTRuaActionPerformed(evt);
            }
        });

        jLEndereco.setText("Numero:");

        jTNumero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTNumeroActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTRua, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLEndereco)
                    .addComponent(jTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(84, 84, 84))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jLEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(103, 103, 103))
        );

        jTTabela.setModel(tmContato);
        jTTabela.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        lsmContato = jTTabela.getSelectionModel();
        lsmContato.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e){
                if (! e.getValueIsAdjusting()){
                    jTTabelaLinhaSelecionada(jTTabela); 
                } 
            } 
        });

        jScrollPane2.setViewportView(jTTabela);

        jBNovo.setText("Novo");
        jBNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBNovoActionPerformed(evt);
            }
        });

        jBAlterarRua.setText("Altera Rua");
        jBAlterarRua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlterarRuaActionPerformed(evt);
            }
        });

        jBAlteraNum.setText("Altera Numero");
        jBAlteraNum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBAlteraNumActionPerformed(evt);
            }
        });

        jBGravar.setText("Gravar");
        jBGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGravarActionPerformed(evt);
            }
        });

        jBExcluir.setText("Excluir");
        jBExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBNovo)
                .addGap(10, 10, 10)
                .addComponent(jBGravar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBExcluir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAlteraNum)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBAlterarRua)
                .addGap(4, 4, 4))
        );

        jPanel3Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {jBExcluir, jBGravar, jBNovo});

        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBNovo)
                    .addComponent(jBAlterarRua)
                    .addComponent(jBAlteraNum)
                    .addComponent(jBGravar)
                    .addComponent(jBExcluir))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jTPesquisa)
                                .addGap(18, 18, 18)
                                .addComponent(jBPesquisar))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBPesquisar)
                    .addComponent(jTPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jBPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBPesquisarActionPerformed
        try {
            listarEnderecos();
        } catch (Exception ex) {
        }
    }//GEN-LAST:event_jBPesquisarActionPerformed

    private void jTRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTRuaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTRuaActionPerformed

    private void jTNumeroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTNumeroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTNumeroActionPerformed

    private void jBNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBNovoActionPerformed
        habilitaDados();
        jTRua.setText("");
        jTNumero.setText("");

    }//GEN-LAST:event_jBNovoActionPerformed
     public boolean verificaDados(){
       if(!jTNumero.getText().equals("") && !jTRua.getText().equals("")){
        
       return true;
     }else{
            JOptionPane.showMessageDialog(null,"Campos Número ou Rua não preenchidos" );
     return false;}
     }
     public void desabilitaDados(){
     jTNumero.setEditable(false);
     jTRua.setEditable(false);     
     }
     public void habilitaDados(){
     jTNumero.setEditable(true);
     jTRua.setEditable(true);
         
     }
     public void listarEnderecos(){
        try {
            Enderecos = EnderecoDAO.leTodosEnd("%"+jTPesquisa.getText()+"%");
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "problema em listar"+ex);
        }
          mostraPesquisa(Enderecos);
     }
     public void mostraPesquisa(List<Endereco> Enderecos){
         while(tmContato.getRowCount()>0){
             tmContato.removeRow(0);
         }
         if(Enderecos.size() == 0){
             JOptionPane.showMessageDialog(null, "Nenhum Endereço Cadastrado");
         }else{
             String[] linha = new String[]{null,null};
             for (int i = 0; i <Enderecos.size(); i++) {
                 tmContato.addRow(linha);
                 tmContato.setValueAt(Enderecos.get(i).getRua(), i, 0 );
                 tmContato.setValueAt(Enderecos.get(i).getNumero(), i, 1 );
             }
         }
     }
     
     private void jTTabelaLinhaSelecionada(JTable tabela) {
        if (jTTabela.getSelectedRow() != -1) {
            jTNumero.setText(String.valueOf(Enderecos.get(tabela.getSelectedRow()).getNumero()));
            jTRua.setText(Enderecos.get(tabela.getSelectedRow()).getRua());
        } else {
            jTNumero.setText("");
            jTRua.setText("");
        }
        
}    public void excluirEndereco(){
    int resp = JOptionPane.showConfirmDialog(this,"Deseja Realmente excluir esse endereço?",
                "Confirmação",JOptionPane.YES_NO_OPTION);
            if(resp == JOptionPane.YES_OPTION ){
                EnderecoDAO dao = new EnderecoDAO();
               try{
                dao.exclui(Enderecos.get(jTTabela.getSelectedRow()).getNumero());
                JOptionPane.showMessageDialog(null, "excluido com sucesso");
                mostraPesquisa(Enderecos);
               }catch(Exception ex){
                   
               }
            }else{
                JOptionPane.showMessageDialog(null, "Cancelado");
            }
}

   private void alteraEnderecoRua(){
       if(jTTabela.getSelectedRow() != -1){
           if(verificaDados()){
               Endereco end = new Endereco();
               end.setRua(jTRua.getText());
               end.setNumero(Integer.parseInt(jTNumero.getText()));
               try {
                   EnderecoDAO.alteraRua(end);
                   JOptionPane.showMessageDialog(null, "Alterado com sucesso");
               } catch (Exception ex) {
                  JOptionPane.showMessageDialog(null, "Erro em Alterar"+ex);
               }
           }
       }
   }
   
    private void alteraEnderecoNum(){
       if(jTTabela.getSelectedRow() != -1){
           if(verificaDados()){
               Endereco end = new Endereco();
               end.setNumero(Integer.parseInt(jTNumero.getText()));
               end.setRua(jTRua.getText());
               try {
                   EnderecoDAO.alteraNumero(end);
                   JOptionPane.showMessageDialog(null, "Alterado com sucesso");
               } catch (Exception ex) {
                  JOptionPane.showMessageDialog(null, "Erro em Alterar"+ex);
               }
           }
       }
   }

    private void jBAlterarRuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlterarRuaActionPerformed
        try {
            alteraEnderecoRua();
            listarEnderecos();
            mostraPesquisa(Enderecos);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Problema no botao Alterar"+ex);
        }
           
        
            
        

    }//GEN-LAST:event_jBAlterarRuaActionPerformed

    private void jBExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBExcluirActionPerformed
        try {
            excluirEndereco();
            listarEnderecos();
            mostraPesquisa(Enderecos);
   
        } catch (Exception ex) {
           JOptionPane.showMessageDialog(null, "Erro em excluir"+ex);
        }
            
            
            
        
    }//GEN-LAST:event_jBExcluirActionPerformed

    private void jBGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGravarActionPerformed
        if(verificaDados()){
            try {
                cadastro();
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso");
                listarEnderecos();
            } catch (Exception ex) {
              JOptionPane.showMessageDialog(null, "Erro em cadastrar"+ex);
            }
            desabilitaDados();
            
        }
    }//GEN-LAST:event_jBGravarActionPerformed

    private void jBAlteraNumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBAlteraNumActionPerformed
      try {
            alteraEnderecoNum();
            listarEnderecos();
            mostraPesquisa(Enderecos);
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Problema no botao Alterar"+ex);
        }
    }//GEN-LAST:event_jBAlteraNumActionPerformed
            public void cadastro() throws Exception{
            Endereco end= new Endereco();
            end.setNumero(Integer.parseInt(jTNumero.getText()));
            end.setRua(jTRua.getText());
            EnderecoDAO.grava(end);
    
            }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroEndereco.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroEndereco().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBAlteraNum;
    private javax.swing.JButton jBAlterarRua;
    private javax.swing.JButton jBExcluir;
    private javax.swing.JButton jBGravar;
    private javax.swing.JButton jBNovo;
    private javax.swing.JButton jBPesquisar;
    private javax.swing.JLabel jLEndereco;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTNumero;
    private javax.swing.JTextField jTPesquisa;
    private javax.swing.JTextField jTRua;
    private javax.swing.JTable jTTabela;
    // End of variables declaration//GEN-END:variables
}
