-- MySQL Script generated by MySQL Workbench
-- 03/12/20 22:18:11
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Livro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Livro` (
  `id` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nome` VARCHAR(100) NULL COMMENT '',
  `Edicao` VARCHAR(6) NULL COMMENT '',
  `Ano` VARCHAR(4) NULL COMMENT '',
  `Descricao` VARCHAR(45) NULL COMMENT '',
  `Prateleira` VARCHAR(10) NULL COMMENT '',
  `ISBN` VARCHAR(25) NULL COMMENT '',
  `RDA` VARCHAR(25) NULL COMMENT '',
  `Editora` VARCHAR(45) NULL COMMENT '',
  PRIMARY KEY (`id`)  COMMENT '')
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
